export const SITE = {
  name: "Silver State IT",
  legalName: "Silver State IT LLC",
  tagline: "Managed IT and cybersecurity for Las Vegas-area businesses",
  hours: "24 hours",
  primaryColor: "#0B1F33",
  accentColor: "#F59E0B",
  defaultOgImagePath: "/og/default.svg",
  url: (import.meta.env.PUBLIC_SITE_URL as string | undefined) || "https://example.com",
  email: (import.meta.env.PUBLIC_CONTACT_EMAIL as string | undefined) || "",
  phone: (import.meta.env.PUBLIC_CONTACT_PHONE as string | undefined) || "",
};

export const SERVICE_AREA = [
  "Las Vegas",
  "North Las Vegas",
  "Henderson",
  "Summerlin",
  "Paradise",
  "Enterprise",
  "Spring Valley",
  "Sunrise Manor",
  "Winchester",
  "Whitney",
  "Centennial Hills",
  "Lone Mountain",
  "Boulder City",
  "Lake Las Vegas",
  "Mesquite",
  "Laughlin",
  "Pahrump",
  "Moapa Valley",
  "Searchlight",
  "Primm",
];
