import type { RelationSet } from "./types";

export const industryRelations: Record<string, RelationSet> = {
  "law-firms": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "managed-cybersecurity-services",
      "microsoft-365",
      "backup-disaster-recovery",
      "email-migration",
      "help-desk-services",
      "cloud-services",
    ],
    locations: [
      "las-vegas-it-services",
      "henderson-it-services",
      "summerlin-it-services",
      "paradise-it-services",
      "spring-valley-it-services",
    ],
  },
  "construction": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "co-managed-it-services",
      "cloud-services",
      "microsoft-windows-365",
      "backup-disaster-recovery",
      "cybersecurity",
      "voip-services-providers",
    ],
    locations: [
      "enterprise-it-services",
      "north-las-vegas-it-services",
      "henderson-it-services",
      "las-vegas-it-services",
      "spring-valley-it-services",
    ],
  },
  "engineering": {
    services: [
      "managed-it-services",
      "co-managed-it-services",
      "cloud-migration",
      "managed-cloud-services",
      "microsoft-azure",
      "backup-disaster-recovery",
      "cybersecurity",
      "hardware-as-a-service",
    ],
    locations: [
      "summerlin-it-services",
      "las-vegas-it-services",
      "henderson-it-services",
      "spring-valley-it-services",
    ],
  },
  "architects": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cloud-services",
      "backup-disaster-recovery",
      "cybersecurity",
      "microsoft-365",
      "hardware-as-a-service",
      "voip-services-providers",
    ],
    locations: [
      "summerlin-it-services",
      "enterprise-it-services",
      "spring-valley-it-services",
      "las-vegas-it-services",
      "henderson-it-services",
    ],
  },
  "manufacturing": {
    services: [
      "managed-it-services",
      "co-managed-it-services",
      "managed-cybersecurity-services",
      "backup-disaster-recovery",
      "cloud-services",
      "microsoft-azure",
      "it-disposition-recycling",
      "hardware-as-a-service",
    ],
    locations: [
      "north-las-vegas-it-services",
      "henderson-it-services",
      "enterprise-it-services",
      "las-vegas-it-services",
      "sunrise-manor-it-services",
    ],
  },
  "real-estate": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "microsoft-365",
      "voip-services-providers",
      "cloud-services",
      "backup-disaster-recovery",
      "hardware-as-a-service",
    ],
    locations: [
      "las-vegas-it-services",
      "summerlin-it-services",
      "henderson-it-services",
      "paradise-it-services",
      "lake-las-vegas-it-services",
    ],
  },
  "professional-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "microsoft-365",
      "cloud-services",
      "backup-disaster-recovery",
      "email-migration",
      "hardware-as-a-service",
      "ai-managed-services",
    ],
    locations: [
      "las-vegas-it-services",
      "summerlin-it-services",
      "henderson-it-services",
      "spring-valley-it-services",
      "enterprise-it-services",
    ],
  },
  "healthcare": {
    services: [
      "managed-it-services",
      "managed-cybersecurity-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "microsoft-365",
      "cloud-services",
      "help-desk-services",
      "it-disposition-recycling",
      "hardware-as-a-service",
    ],
    locations: [
      "las-vegas-it-services",
      "henderson-it-services",
      "summerlin-it-services",
      "spring-valley-it-services",
      "paradise-it-services",
      "north-las-vegas-it-services",
    ],
  },
  "nonprofits": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "microsoft-365",
      "microsoft-office-365",
      "email-migration",
      "cybersecurity",
      "backup-disaster-recovery",
      "hardware-as-a-service",
    ],
    locations: [
      "las-vegas-it-services",
      "henderson-it-services",
      "north-las-vegas-it-services",
      "sunrise-manor-it-services",
      "boulder-city-it-services",
    ],
  },
  "insurance": {
    services: [
      "cybersecurity",
      "cybersecurity-insurance",
      "managed-cybersecurity-services",
      "microsoft-365",
      "backup-disaster-recovery",
      "managed-it-services",
      "help-desk-services",
      "cloud-services",
    ],
    locations: [
      "las-vegas-it-services",
      "henderson-it-services",
      "summerlin-it-services",
      "enterprise-it-services",
      "spring-valley-it-services",
    ],
  },
  "cpa-accountant": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "microsoft-365",
      "email-migration",
      "backup-disaster-recovery",
      "help-desk-services",
      "cloud-services",
      "hardware-as-a-service",
    ],
    locations: [
      "las-vegas-it-services",
      "henderson-it-services",
      "summerlin-it-services",
      "spring-valley-it-services",
      "paradise-it-services",
    ],
  },
  "marketing": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cloud-services",
      "microsoft-azure",
      "backup-disaster-recovery",
      "cybersecurity",
      "ai-managed-services",
      "hardware-as-a-service",
    ],
    locations: [
      "summerlin-it-services",
      "las-vegas-it-services",
      "spring-valley-it-services",
      "henderson-it-services",
      "enterprise-it-services",
    ],
  },
  "business-services": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "cloud-services",
      "microsoft-365",
      "backup-disaster-recovery",
      "voip-services-providers",
      "hardware-as-a-service",
    ],
    locations: [
      "las-vegas-it-services",
      "north-las-vegas-it-services",
      "henderson-it-services",
      "paradise-it-services",
      "winchester-it-services",
    ],
  },
  "printing-services": {
    services: [
      "managed-it-services",
      "co-managed-it-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "help-desk-services",
      "cloud-services",
      "microsoft-365",
      "it-disposition-recycling",
    ],
    locations: [
      "north-las-vegas-it-services",
      "sunrise-manor-it-services",
      "las-vegas-it-services",
      "henderson-it-services",
    ],
  },
  "hospitality": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "voip-services-providers",
      "cloud-services",
      "microsoft-365",
      "hardware-as-a-service",
      "co-managed-it-services",
    ],
    locations: [
      "paradise-it-services",
      "las-vegas-it-services",
      "winchester-it-services",
      "enterprise-it-services",
      "laughlin-it-services",
      "primm-it-services",
    ],
  },
  "gaming": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "managed-cybersecurity-services",
      "backup-disaster-recovery",
      "co-managed-it-services",
      "cloud-services",
      "microsoft-azure",
      "help-desk-services",
    ],
    locations: ["paradise-it-services", "winchester-it-services", "las-vegas-it-services", "laughlin-it-services"],
  },
  "casino": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "help-desk-services",
      "voip-services-providers",
      "co-managed-it-services",
      "cloud-services",
      "it-disposition-recycling",
    ],
    locations: ["paradise-it-services", "winchester-it-services", "las-vegas-it-services", "laughlin-it-services", "primm-it-services"],
  },
  "hotels": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "backup-disaster-recovery",
      "cybersecurity",
      "voip-services-providers",
      "cloud-services",
      "co-managed-it-services",
      "hardware-as-a-service",
    ],
    locations: ["paradise-it-services", "winchester-it-services", "las-vegas-it-services", "henderson-it-services", "laughlin-it-services"],
  },
  "medical": {
    services: [
      "managed-it-services",
      "managed-cybersecurity-services",
      "backup-disaster-recovery",
      "cybersecurity",
      "microsoft-365",
      "help-desk-services",
      "cloud-services",
      "it-disposition-recycling",
      "hardware-as-a-service",
    ],
    locations: ["henderson-it-services", "summerlin-it-services", "las-vegas-it-services", "spring-valley-it-services"],
  },
  "hospitals": {
    services: [
      "managed-it-services",
      "managed-cybersecurity-services",
      "backup-disaster-recovery",
      "microsoft-azure",
      "cloud-services",
      "co-managed-it-services",
      "help-desk-services",
      "it-disposition-recycling",
    ],
    locations: ["las-vegas-it-services", "henderson-it-services", "summerlin-it-services", "paradise-it-services", "north-las-vegas-it-services"],
  },
  "medical-spas": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "voip-services-providers",
      "cloud-services",
      "backup-disaster-recovery",
      "microsoft-365",
      "hardware-as-a-service",
    ],
    locations: ["summerlin-it-services", "henderson-it-services", "spring-valley-it-services", "enterprise-it-services"],
  },
  "logistics": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "cloud-services",
      "managed-cloud-services",
      "backup-disaster-recovery",
      "help-desk-services",
      "microsoft-azure",
      "hardware-as-a-service",
    ],
    locations: ["north-las-vegas-it-services", "enterprise-it-services", "henderson-it-services", "las-vegas-it-services", "primm-it-services"],
  },
  "startups": {
    services: [
      "managed-it-services",
      "cloud-services",
      "managed-cloud-services",
      "cybersecurity",
      "microsoft-windows-365",
      "microsoft-azure",
      "hardware-as-a-service",
      "ai-managed-services",
    ],
    locations: ["las-vegas-it-services", "summerlin-it-services", "henderson-it-services", "spring-valley-it-services"],
  },
  "small-mid-sized-businesses": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "cloud-services",
      "microsoft-365",
      "voip-services-providers",
      "hardware-as-a-service",
      "it-disposition-recycling",
    ],
    locations: [
      "las-vegas-it-services",
      "henderson-it-services",
      "north-las-vegas-it-services",
      "spring-valley-it-services",
      "summerlin-it-services",
      "enterprise-it-services",
    ],
  },
};
