import type { RelationSet } from "./types";

export const locationRelations: Record<string, RelationSet> = {
  "las-vegas-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "microsoft",
      "backup-disaster-recovery",
      "cloud-services",
      "co-managed-it-services",
      "email-migration",
      "voip-services-providers",
    ],
    industries: [
      "professional-services",
      "law-firms",
      "healthcare",
      "construction",
      "gaming",
      "small-mid-sized-businesses",
    ],
    nearbyLocations: [
      "winchester-it-services",
      "paradise-it-services",
      "spring-valley-it-services",
      "north-las-vegas-it-services",
    ],
  },
  "primm-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "cloud-services",
      "voip-services-providers",
      "hardware-as-a-service",
    ],
    industries: ["hospitality", "hotels", "casino", "logistics"],
    nearbyLocations: ["enterprise-it-services", "pahrump-it-services", "las-vegas-it-services"],
  },
  "lake-las-vegas-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "microsoft-365",
      "cloud-services",
      "backup-disaster-recovery",
      "voip-services-providers",
    ],
    industries: ["real-estate", "professional-services", "medical-spas", "insurance"],
    nearbyLocations: ["henderson-it-services", "boulder-city-it-services", "whitney-it-services"],
  },
  "pahrump-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "cloud-services",
      "microsoft-365",
      "voip-services-providers",
    ],
    industries: ["medical", "professional-services", "construction", "real-estate", "small-mid-sized-businesses"],
    nearbyLocations: ["primm-it-services", "las-vegas-it-services", "spring-valley-it-services"],
  },
  "enterprise-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "cloud-services",
      "cloud-migration",
      "microsoft-azure",
      "backup-disaster-recovery",
      "voip-services-providers",
    ],
    industries: ["construction", "hospitality", "logistics", "business-services", "startups"],
    nearbyLocations: ["spring-valley-it-services", "paradise-it-services", "henderson-it-services"],
  },
  "moapa-valley-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "help-desk-services",
      "cloud-services",
      "microsoft-365",
      "hardware-as-a-service",
    ],
    industries: ["nonprofits", "medical", "construction", "business-services"],
    nearbyLocations: ["mesquite-it-services", "north-las-vegas-it-services", "las-vegas-it-services"],
  },
  "boulder-city-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "help-desk-services",
      "microsoft-365",
      "cloud-services",
      "it-disposition-recycling",
    ],
    industries: ["professional-services", "construction", "nonprofits", "medical", "small-mid-sized-businesses"],
    nearbyLocations: ["henderson-it-services", "searchlight-it-services", "lake-las-vegas-it-services"],
  },
  "whitney-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "microsoft-365",
      "cloud-services",
      "hardware-as-a-service",
    ],
    industries: ["medical", "healthcare", "business-services", "real-estate", "professional-services"],
    nearbyLocations: ["henderson-it-services", "sunrise-manor-it-services", "paradise-it-services"],
  },
  "north-las-vegas-it-services": {
    services: [
      "managed-it-services",
      "co-managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "cloud-services",
      "hardware-as-a-service",
      "it-disposition-recycling",
    ],
    industries: ["manufacturing", "logistics", "printing-services", "business-services", "construction"],
    nearbyLocations: ["centennial-hills-it-services", "las-vegas-it-services", "sunrise-manor-it-services"],
  },
  "searchlight-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "help-desk-services",
      "cloud-services",
      "microsoft-365",
    ],
    industries: ["construction", "business-services", "nonprofits", "medical"],
    nearbyLocations: ["boulder-city-it-services", "henderson-it-services", "laughlin-it-services"],
  },
  "summerlin-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "microsoft",
      "cloud-services",
      "managed-cloud-services",
      "backup-disaster-recovery",
      "ai-managed-services",
    ],
    industries: ["professional-services", "law-firms", "marketing", "real-estate", "medical-spas"],
    nearbyLocations: [
      "lone-mountain-it-services",
      "spring-valley-it-services",
      "las-vegas-it-services",
      "centennial-hills-it-services",
    ],
  },
  "paradise-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "voip-services-providers",
      "co-managed-it-services",
      "microsoft-365",
      "cloud-services",
    ],
    industries: ["hospitality", "hotels", "casino", "gaming", "professional-services"],
    nearbyLocations: ["winchester-it-services", "enterprise-it-services", "las-vegas-it-services"],
  },
  "laughlin-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "voip-services-providers",
      "co-managed-it-services",
      "cloud-services",
    ],
    industries: ["hospitality", "hotels", "casino", "gaming", "business-services"],
    nearbyLocations: ["searchlight-it-services", "mesquite-it-services", "las-vegas-it-services"],
  },
  "winchester-it-services": {
    services: [
      "help-desk-services",
      "managed-it-services",
      "cybersecurity",
      "microsoft-365",
      "backup-disaster-recovery",
      "cloud-services",
      "email-migration",
    ],
    industries: ["hotels", "casino", "gaming", "professional-services", "marketing"],
    nearbyLocations: ["paradise-it-services", "las-vegas-it-services", "sunrise-manor-it-services"],
  },
  "sunrise-manor-it-services": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "backup-disaster-recovery",
      "cloud-services",
      "hardware-as-a-service",
      "it-disposition-recycling",
    ],
    industries: ["printing-services", "nonprofits", "business-services", "logistics", "healthcare"],
    nearbyLocations: ["las-vegas-it-services", "whitney-it-services", "north-las-vegas-it-services"],
  },
  "henderson-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "managed-cybersecurity-services",
      "microsoft-365",
      "cloud-services",
      "backup-disaster-recovery",
      "email-migration",
      "voip-services-providers",
      "hardware-as-a-service",
    ],
    industries: ["healthcare", "medical", "professional-services", "insurance", "real-estate", "small-mid-sized-businesses"],
    nearbyLocations: ["lake-las-vegas-it-services", "whitney-it-services", "enterprise-it-services", "paradise-it-services"],
  },
  "mesquite-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "cloud-services",
      "voip-services-providers",
      "microsoft-365",
    ],
    industries: ["hospitality", "hotels", "medical", "real-estate", "small-mid-sized-businesses"],
    nearbyLocations: ["moapa-valley-it-services", "las-vegas-it-services"],
  },
  "centennial-hills-it-services": {
    services: [
      "managed-it-services",
      "cybersecurity",
      "help-desk-services",
      "backup-disaster-recovery",
      "cloud-services",
      "hardware-as-a-service",
      "co-managed-it-services",
    ],
    industries: ["construction", "professional-services", "real-estate", "business-services"],
    nearbyLocations: ["lone-mountain-it-services", "north-las-vegas-it-services", "summerlin-it-services"],
  },
  "lone-mountain-it-services": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "microsoft-365",
      "backup-disaster-recovery",
      "cloud-services",
      "hardware-as-a-service",
    ],
    industries: ["professional-services", "law-firms", "medical-spas", "real-estate"],
    nearbyLocations: ["summerlin-it-services", "centennial-hills-it-services", "spring-valley-it-services"],
  },
  "spring-valley-it-services": {
    services: [
      "managed-it-services",
      "help-desk-services",
      "cybersecurity",
      "microsoft-365",
      "cloud-services",
      "voip-services-providers",
      "backup-disaster-recovery",
      "email-migration",
    ],
    industries: ["business-services", "marketing", "professional-services", "real-estate", "medical-spas"],
    nearbyLocations: ["summerlin-it-services", "enterprise-it-services", "paradise-it-services", "las-vegas-it-services"],
  },
};

